project:
  type: website
  output-dir: _site
  files:
    - index.qmd
    - about.qmd
    - Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
    - Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd

website:
  title: "ISSS608-VAA"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 1"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

